kind: Service
apiVersion: v1
metadata:
  name: consumer-service
spec:
  selector:
    app: test-client
  ports:
  - protocol: TCP
    port: 8090
    nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  selector:
    matchLabels:
      app: consumer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: consumer-service
        image: consumer-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090