spring:
  application:
    name: product-service
  profiles:
    active: dev
  cache:
    cache-names: resourceCache,metaCache,codeSetCache,schemaCache
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=600s

server:
  port: 9088
core:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/frameset?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
  username: root
  password: root

project:
  queryConfigPath: classpath:queryConfig

logging:
  config: classpath:logback-spring.xml
log:
  level: ERROR
  home: ./logs