spring:
  application:
    name: product-service
  profiles:
    active: dev
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=robinjim
        healthCheckInterval: 5s
        healthCheckPath: /health
        register: true
        service-name: product-service
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
  messages:
    basename: i18n/messages
    encoding: UTF-8



server:
  port: 9088
core:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/frameset?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
  username: root
  password: root

project:
  queryConfigPath: classpath:queryConfig

logging:
  config: classpath:logback-spring.xml

log:
  level: INFO
  home: ./logs
auth-server-url: http://AUTH-SERVICE

login:
  ignoreUrls: /login,/logout,/health,/error,/user/login,/swagger-ui.html,/swagger**,/webjars/**,/v2/api-docs/**,/swagger-resources/**
  ignoreResources: gif,bmp,png,jpg,js,flash,css,swf,flv,metaget
  oauth2-uri: http://gateway-service/oauth2/
  clientId: webui-client
  clientSecret: 123456

security:
  oauth2:
    client:
      client-id: webclient_id
      client-secret: 123456
      scope: read_userinfo
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token
      check-token: ${auth-server-url}/oauth/check_token

email:
  fromMailBox: 1@11.com