frame:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://localhost:3316/frameset?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

