spring:
  datasource:
    hikari:
        jdbc-url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
        driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  application:
    name: oauth2-authserver
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        tags: version=1.0,author=robinjim
        healthCheckInterval: 50s
        healthCheckPath: /health
        service-name: oauth2-service

  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 10
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8

  messages:
    basename: i18n/messages




server:
  port: 9098
  servlet:
    session:
      timeout: "PT10M"
    context-path: /

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework:
        security: debug
log:
  level: DEBUG
  home: ./logs

login:
  ignoreUrls: /oauth/**,/webjars/**,login,logout,/health,/error,/user/login
  ignoreResources: gif,bmp,png,jpg,js,flash,css,swf,flv,metaget

static:
  uriPrefix: http://localhost:80

backgroud:
  serverUrl: http://gateway-service/product/


project:
  queryConfigPath: classpath:queryConfig